# Generated by Django 5.2 on 2025-07-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(default=0)),
                ('password', models.CharField(default='', max_length=500)),
                ('role', models.CharField(default='Student', max_length=10)),
            ],
        ),
    ]
